name: Test Github actions
on:
  push:
    branches:
      - dev
      - release/*
jobs:
    Deployment: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build Next.js app
              run: npm run build
              
            - name: Run Tests
              run: npm test
              
